import type { Artist } from '@/types';

export const artists: Artist[] = [
  {
    id: 'artist-1',
    slug: 'divine',
    name: 'Divine',
    avatar: '/artist/artist1.jpeg',
    bio: "Vivian Fernandes, known as Divine, is one of India's most prominent rappers from Mumbai. Rising from the streets of Andheri, he's known for powerful tracks like 'Mere Gully Mein' and collaborations with Nucleya. His raw, authentic style represents the voice of Mumbai's youth.",
    socials: {
      instagram: 'https://instagram.com/vivianakadivine',
      youtube: 'https://youtube.com/@DivineMusic',
      spotify: 'https://open.spotify.com/artist/1z6FCVjbusHlS6mZgZwAkW',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
    ],
    basePrice: 2500000,
    genres: ['Hip-Hop', 'Rap', 'Mumbai', 'Bollywood', 'Street'],
    isBookable: true,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-01-10T09:00:00Z',
  },
  {
    id: 'artist-2',
    slug: 'encore-abj',
    name: 'Encore',
    avatar: '/artist/artist2.jpeg',
    bio: "Abhijay Negi, better known as Encore ABJ, is a Delhi-based rapper known for his melodic rap style and emotional depth. He gained recognition with tracks like 'Zindagi' and has been a consistent presence in the Indian hip-hop scene since 2017.",
    socials: {
      instagram: 'https://instagram.com/encoreabj',
      youtube: 'https://youtube.com/@EncoreABJ',
      spotify: 'https://open.spotify.com/artist/encore-abj',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    ],
    basePrice: 800000, // 8 lakhs
    // rating: 4.7,
    genres: ['Hip-Hop', 'Melodic Rap', 'Delhi', 'Emotional', 'Underground'],
    // categories: ["Hip-Hop", "Melodic Rap", "Live Performance", "Underground"],
    // availability: ["2024-12-25", "2024-12-26", "2024-12-27", "2024-12-28"],
    // timeSlots: ["18:00", "19:00", "20:00", "21:00", "22:00"],
    isBookable: true,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-02-05T11:15:00Z',
  },
  {
    id: 'artist-3',
    slug: 'krsna',
    name: 'KR$NA',
    avatar: '/artist/artist3.jpeg',
    bio: "Krishna Kaul, known as KR$NA, is one of India's most technically skilled rappers. Known for his complex wordplay, rapid-fire delivery, and tracks like 'No Cap' and 'Overdrive'. He's considered among the best lyricists in the Indian hip-hop scene.",
    socials: {
      instagram: 'https://instagram.com/realkrsna',
      youtube: 'https://youtube.com/@KRSNAMUSIC',
      spotify: 'https://open.spotify.com/artist/krsna-official',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    ],
    basePrice: 1500000, // 15 lakhs
    // rating: 4.8,
    genres: ['Hip-Hop', 'Rap', 'Lyrical', 'Technical', 'Underground'],
    // categories: ["Hip-Hop", "Rap", "Live Performance", "Battle Rap"],
    // availability: [
    //   "2024-12-25",
    //   "2024-12-26",
    //   "2024-12-27",
    //   "2024-12-28",
    //   "2024-12-29",
    // ],
    // timeSlots: ["19:00", "20:00", "21:00", "22:00"],
    isBookable: true,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-01-25T16:45:00Z',
  },
  {
    id: 'artist-4',
    slug: 'raga',
    name: 'Raga',
    avatar: '/artist/artist4.jpeg',
    bio: "Raghav Sharma, known as Raga, is a Mumbai-based rapper and producer known for his versatile style that blends traditional Indian elements with modern hip-hop. He's gained recognition for his storytelling abilities and melodic approach to rap.",
    socials: {
      instagram: 'https://instagram.com/raga_official',
      youtube: 'https://youtube.com/@RagaOfficial',
      soundcloud: 'https://soundcloud.com/raga-official',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=600&fit=crop',
    ],
    basePrice: 600000, // 6 lakhs
    // rating: 4.6,
    genres: ['Hip-Hop', 'Producer', 'Storytelling', 'Melodic', 'Mumbai'],
    // categories: ["Hip-Hop", "Producer", "Live Performance", "Storytelling"],
    // availability: ["2024-12-25", "2024-12-26", "2024-12-27"],
    // timeSlots: ["18:00", "19:00", "20:00", "21:00"],
    isBookable: true,
    appealStatus: 'approved',
    createdAt: '2024-03-01T13:20:00Z',
  },
  {
    id: 'artist-5',
    slug: 'talwiinder',
    name: 'Talwiinder',
    avatar: '/artist/artist5.jpeg',
    bio: 'Talwiinder is a Punjabi rapper known for blending traditional Punjabi music with contemporary hip-hop beats. His unique style bridges the gap between regional and mainstream Indian hip-hop, making him popular across diverse audiences.',
    socials: {
      instagram: 'https://instagram.com/talwiinder',
      youtube: 'https://youtube.com/@TalwiinderOfficial',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
    ],
    basePrice: 500000, // 5 lakhs
    // rating: 4.5,
    genres: ['Punjabi Rap', 'Hip-Hop', 'Regional', 'Fusion', 'Traditional'],
    // categories: [
    //   "Punjabi Rap",
    //   "Hip-Hop",
    //   "Regional Music",
    //   "Live Performance",
    // ],
    // availability: [
    //   "2024-12-25",
    //   "2024-12-26",
    //   "2024-12-27",
    //   "2024-12-28",
    //   "2024-12-29",
    //   "2024-12-30",
    // ],
    // timeSlots: ["19:00", "20:00", "21:00", "22:00"],
    isBookable: true,
    appealStatus: 'approved',
    createdAt: '2024-02-15T10:30:00Z',
  },
  {
    id: 'artist-6',
    slug: 'calm',
    name: 'Calm',
    avatar: '/artist/artist6.jpeg',
    bio: 'Calm is an emerging Indian rapper known for his introspective lyrics and chill, laid-back delivery style. His music often explores themes of mental health, relationships, and personal growth, resonating with the younger generation of hip-hop listeners.',
    socials: {
      instagram: 'https://instagram.com/calm_rapper',
      youtube: 'https://youtube.com/@CalmOfficial',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
    ],
    basePrice: 300000, // 3 lakhs
    // rating: 4.4,
    genres: [
      'Hip-Hop',
      'Introspective',
      'Chill',
      'Mental Health',
      'Underground',
    ],
    // categories: [
    //   "Hip-Hop",
    //   "Alternative Rap",
    //   "Live Performance",
    //   "Underground",
    // ],
    // availability: [
    //   "2024-12-25",
    //   "2024-12-26",
    //   "2024-12-27",
    //   "2024-12-28",
    //   "2024-12-29",
    //   "2024-12-30",
    // ],
    // timeSlots: ["18:00", "19:00", "20:00", "21:00"],
    isBookable: true,
    appealStatus: 'approved',
    createdAt: '2024-02-15T10:30:00Z',
  },
  {
    id: 'artist-7',
    slug: 'hanumankind',
    name: 'Hanumankind',
    avatar: '/artist/artist7.jpeg',
    bio: "Sooraj Cherukat, known as Hanumankind, is a Kerala-based rapper who gained massive recognition with his viral hit 'Big Dawgs'. Known for his distinctive flow and representation of South Indian hip-hop culture, he's become one of the most talked-about artists in recent times.",
    socials: {
      instagram: 'https://instagram.com/hanumankind',
      youtube: 'https://youtube.com/@Hanumankind',
      spotify: 'https://open.spotify.com/artist/hanumankind',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
    ],
    basePrice: 1200000, // 12 lakhs
    // rating: 4.8,
    genres: ['Hip-Hop', 'South Indian', 'Viral', 'Kerala', 'Regional'],
    // categories: ["Hip-Hop", "Regional Rap", "Live Performance", "Viral Artist"],
    // availability: [
    //   "2024-12-25",
    //   "2024-12-26",
    //   "2024-12-27",
    //   "2024-12-28",
    //   "2024-12-29",
    //   "2024-12-30",
    // ],
    // timeSlots: ["19:00", "20:00", "21:00", "22:00"],
    isBookable: false,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-02-15T10:30:00Z',
  },
  {
    id: 'artist-8',
    slug: 'emiway-bantai',
    name: 'Emiway',
    avatar: '/artist/artist8.jpeg',
    bio: "Bilal Shaikh, known as Emiway Bantai, is one of India's most prominent independent rappers from Mumbai. Born in Bengaluru and raised in Mumbai, he rose to fame with tracks like 'Machayenge', 'Asli Hip Hop', and 'Aur Bantai'. Known for his raw, street-style rap and independent approach to music.",
    socials: {
      instagram: 'https://instagram.com/emiwaybantai',
      youtube: 'https://youtube.com/@EmiwayBantai',
      spotify: 'https://open.spotify.com/artist/emiway-bantai',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
    ],
    basePrice: 2000000, // 20 lakhs
    // rating: 4.8,
    genres: ['Hip-Hop', 'Independent', 'Mumbai', 'Street Rap', 'Bollywood'],
    // categories: [
    //   "Hip-Hop",
    //   "Independent Artist",
    //   "Live Performance",
    //   "Street Rap",
    // ],
    // availability: [
    //   "2024-12-25",
    //   "2024-12-26",
    //   "2024-12-27",
    //   "2024-12-28",
    //   "2024-12-29",
    //   "2024-12-30",
    //   "2024-12-31",
    // ],
    // timeSlots: ["19:00", "20:00", "21:00", "22:00"],
    isBookable: false,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-01-15T14:30:00Z',
  },
  {
    id: 'artist-9',
    slug: 'raftaar',
    name: 'Raftaar',
    avatar: '/artist/artist9.jpeg',
    bio: "Dilin Nair, known as Raftaar, is a pioneering figure in Indian hip-hop. Born in Trivandrum and raised in Delhi, he's known for hits like 'Swag Mera Desi', 'All Black', and his work in Bollywood. He founded the record label KALAMKAAR and has been a judge on MTV Hustle, playing a crucial role in developing Indian hip-hop talent.",
    socials: {
      instagram: 'https://instagram.com/raftaarmusic',
      youtube: 'https://youtube.com/@RaftaarMusic',
      spotify: 'https://open.spotify.com/artist/raftaar',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1516280440614-37939bbacd81?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    ],
    basePrice: 3000000, // 30 lakhs
    // rating: 4.9,
    genres: ['Hip-Hop', 'Producer', 'Bollywood', 'Judge', 'KALAMKAAR'],
    // categories: ["Hip-Hop", "Music Producer", "Bollywood", "Live Performance"],
    // availability: ["2024-12-25", "2024-12-26", "2024-12-27", "2024-12-28"],
    // timeSlots: ["18:00", "19:00", "20:00", "21:00", "22:00"],
    isBookable: false,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-01-20T16:45:00Z',
  },
  {
    id: 'artist-10',
    slug: 'king',
    name: 'King',
    avatar: '/artist/artist10.jpeg',
    bio: "Arpan Kumar Chandel, professionally known as King, is one of India's fastest-growing music artists. From Delhi, he rose to fame through MTV Hustle and became a global sensation with 'Maan Meri Jaan', which was the most streamed song of 2023 on Spotify India. Known for his melodic rap style and emotional depth in songs.",
    socials: {
      instagram: 'https://instagram.com/iamkingindian',
      youtube: 'https://youtube.com/@KingRocco',
      spotify: 'https://open.spotify.com/artist/king-rocco',
    },
    embeds: {
      youtube: 'https://www.youtube.com/watch?v=XCIYHCXQoxQ',
      spotify: 'https://open.spotify.com/track/19pHSvXUwErAXFktkvYMk9',
      soundcloud:
        'https://soundcloud.com/ender-gaming-531387957/seedhe-maut-raat-ki-raani',
    },
    photos: [
      'https://images.unsplash.com/photo-1511379938547-c1f69419868d?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop',
    ],
    basePrice: 1800000, // 18 lakhs
    // rating: 4.8,
    genres: ['Hip-Hop', 'Melodic Rap', 'MTV Hustle', 'Pop Rap', 'Commercial'],
    // categories: ["Hip-Hop", "Pop Rap", "Commercial Music", "Live Performance"],
    // availability: [
    //   "2024-12-25",
    //   "2024-12-26",
    //   "2024-12-27",
    //   "2024-12-28",
    //   "2024-12-29",
    // ],
    // timeSlots: ["18:00", "19:00", "20:00", "21:00", "22:00"],
    isBookable: true,
    appealStatus: 'approved',
    featured: true,
    createdAt: '2024-01-25T12:15:00Z',
  },
];
