export const dummyDashboardData = {
  stats: {
    totalBookings: 45,
    totalEarnings: 2250000,
    averageRating: 4.8,
    responseTime: '2 hours',
    completionRate: 98,
    profileViews: 247,
    bookingRequests: 23,
    conversionRate: 68,
  },
  recentBookings: [
    {
      id: '1',
      eventType: 'Wedding Reception',
      clientName: 'Priya & Raj',
      date: '2025-01-15',
      amount: 85000,
      status: 'confirmed',
      location: 'Mumbai',
    },
    {
      id: '2',
      eventType: 'Birthday Party',
      clientName: 'Sharma Family',
      date: '2025-01-28',
      amount: 45000,
      status: 'pending',
      location: 'Delhi',
    },
    {
      id: '3',
      eventType: 'Corporate Event',
      clientName: 'Tech Corp',
      date: '2025-02-05',
      amount: 120000,
      status: 'confirmed',
      location: 'Bangalore',
    },
    {
      id: '4',
      eventType: 'Festival Performance',
      clientName: 'Cultural Society',
      date: '2025-02-15',
      amount: 65000,
      status: 'pending',
      location: 'Pune',
    },
  ],
  monthlyData: [
    { month: 'Oct', bookings: 8, earnings: 400000 },
    { month: 'Nov', bookings: 12, earnings: 600000 },
    { month: 'Dec', bookings: 15, earnings: 750000 },
    { month: 'Jan', bookings: 10, earnings: 500000 },
  ],
  upcomingBookings: [
    { date: '2025-01-15', event: 'Wedding Reception', location: 'Mumbai' },
    { date: '2025-01-28', event: 'Birthday Party', location: 'Delhi' },
    { date: '2025-02-05', event: 'Corporate Event', location: 'Bangalore' },
  ],
  notifications: [
    {
      id: 1,
      type: 'booking',
      message: 'New booking request from Sharma Family',
      time: '2 hours ago',
      unread: true,
    },
    {
      id: 2,
      type: 'payment',
      message: 'Payment received for Wedding Reception - ₹85,000',
      time: '1 day ago',
      unread: false,
    },
    {
      id: 3,
      type: 'review',
      message: 'New 5-star review from Priya & Raj',
      time: '2 days ago',
      unread: false,
    },
  ],
};
