import type { Tag } from "./types";

export const tags: Tag[] = [
  { id: "tag-1", name: "DJ", color: "bg-purple-500" },
  { id: "tag-2", name: "Electronic", color: "bg-blue-500" },
  { id: "tag-3", name: "Classical", color: "bg-yellow-500" },
  { id: "tag-4", name: "Violin", color: "bg-green-500" },
  { id: "tag-5", name: "Jazz", color: "bg-orange-500" },
  { id: "tag-6", name: "Saxophone", color: "bg-red-500" },
  { id: "tag-7", name: "Rock", color: "bg-gray-500" },
  { id: "tag-8", name: "Pop", color: "bg-pink-500" },
  { id: "tag-9", name: "Hip-Hop", color: "bg-indigo-500" },
  { id: "tag-10", name: "Country", color: "bg-brown-500" },
  { id: "tag-11", name: "Blues", color: "bg-blue-600" },
  { id: "tag-12", name: "Folk", color: "bg-green-600" },
  { id: "tag-13", name: "Latin", color: "bg-red-600" },
  { id: "tag-14", name: "Weddings", color: "bg-pink-400" },
  { id: "tag-15", name: "Corporate", color: "bg-gray-600" },
  { id: "tag-16", name: "Solo", color: "bg-purple-600" },
  { id: "tag-17", name: "Band", color: "bg-orange-600" },
  { id: "tag-18", name: "Intimate", color: "bg-green-400" },
  { id: "tag-19", name: "Elegant", color: "bg-yellow-600" },
  { id: "tag-20", name: "Sophisticated", color: "bg-indigo-600" },
  { id: "tag-21", name: "Traditional", color: "bg-brown-600" },
  { id: "tag-22", name: "Clubs", color: "bg-purple-400" },
  { id: "tag-23", name: "Singer-Songwriter", color: "bg-blue-400" },
  { id: "tag-24", name: "Acoustic", color: "bg-green-500" },
  { id: "tag-25", name: "Guitar", color: "bg-orange-400" },
  { id: "tag-26", name: "Vocalist", color: "bg-red-400" },
];
