// Dummy user dashboard data - in real app, fetch from API based on user ID
export const dummyUserDashboardData = {
  user: {
    id: 'user-123',
    name: 'Vikash Gupta',
    email: 'vikash@example.com',
    avatar: '/images/user-placeholder.jpg',
    memberSince: '2024-01-20',
    location: 'Mumbai, Maharashtra',
  },
  stats: {
    totalBookings: 12,
    totalSpent: 850000,
    averageRating: 4.6,
    savedArtists: 8,
    upcomingEvents: 2,
    completedEvents: 10,
  },
  recentBookings: [
    {
      id: '1',
      artistName: 'Rajesh Kumar',
      artistSlug: 'rajesh-kumar',
      artistAvatar: '/images/artist-1.jpg',
      eventType: 'Wedding Reception',
      date: '2025-01-15',
      amount: 85000,
      status: 'confirmed',
      location: 'Mumbai',
      rating: null,
    },
    {
      id: '2',
      artistName: 'Priya Singh',
      artistSlug: 'priya-singh',
      artistAvatar: '/images/artist-2.jpg',
      eventType: 'Birthday Party',
      date: '2025-02-20',
      amount: 55000,
      status: 'pending',
      location: 'Delhi',
      rating: null,
    },
    {
      id: '3',
      artistName: 'Amit Sharma',
      artistSlug: 'amit-sharma',
      artistAvatar: '/images/artist-3.jpg',
      eventType: 'Anniversary Celebration',
      date: '2024-12-15',
      amount: 75000,
      status: 'completed',
      location: 'Pune',
      rating: 5,
    },
    {
      id: '4',
      artistName: 'Neha Patel',
      artistSlug: 'neha-patel',
      artistAvatar: '/images/artist-4.jpg',
      eventType: 'Corporate Event',
      date: '2024-11-28',
      amount: 120000,
      status: 'completed',
      location: 'Bangalore',
      rating: 4,
    },
  ],
  savedArtists: [
    {
      id: '1',
      name: 'Rajesh Kumar',
      slug: 'rajesh-kumar',
      avatar: '/images/artist-1.jpg',
      rating: 4.8,
      price: 75000,
      categories: ['Classical', 'Bollywood'],
      isBookable: true,
    },
    {
      id: '2',
      name: 'Kavita Krishnamurthy',
      slug: 'kavita-krishnamurthy',
      avatar: '/images/artist-2.jpg',
      rating: 4.9,
      price: 150000,
      categories: ['Classical', 'Devotional'],
      isBookable: true,
    },
    {
      id: '3',
      name: 'Arijit Singh',
      slug: 'arijit-singh',
      avatar: '/images/artist-3.jpg',
      rating: 4.7,
      price: 200000,
      categories: ['Bollywood', 'Romance'],
      isBookable: false,
    },
  ],
  upcomingEvents: [
    {
      id: '1',
      artistName: 'Rajesh Kumar',
      eventType: 'Wedding Reception',
      date: '2025-01-15',
      location: 'Mumbai',
      amount: 85000,
      status: 'confirmed',
    },
    {
      id: '2',
      artistName: 'Priya Singh',
      eventType: 'Birthday Party',
      date: '2025-02-20',
      location: 'Delhi',
      amount: 55000,
      status: 'pending',
    },
  ],
  recommendations: [
    {
      id: '1',
      name: 'Sunidhi Chauhan',
      slug: 'sunidhi-chauhan',
      avatar: '/images/artist-rec-1.jpg',
      rating: 4.8,
      price: 180000,
      categories: ['Bollywood', 'Pop'],
      reason: 'Based on your previous bookings',
    },
    {
      id: '2',
      name: 'Shankar Mahadevan',
      slug: 'shankar-mahadevan',
      avatar: '/images/artist-rec-2.jpg',
      rating: 4.9,
      price: 220000,
      categories: ['Classical', 'Fusion'],
      reason: 'Trending in your area',
    },
  ],
};
